### PR TITLE
add api functionality

### PR DESCRIPTION
**Pull request by mj-e-boc**
-Implement api functionality
-Fix html,
-Fix linter errors

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @mj-e-boc, you have submitted a project that does not follow Git flow can you switch the main branch to dev branch in your pr? See an example below ⬇️ 
WHKrh

**Review by julie-ify — COMMENTED** [review]
Hi @mj-e-boc,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* You have submitted a project which did not follow the required flow. You should use Gitflow, which means we should be merging to dev branch, not main branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
Hi @mj-e-boc,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Git flow Not Used ⚠️

- Pull request is to be made from the feature branch into the develop or dev branch not into the main or master branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by OLIPLICHE — APPROVED** [review]
Hi @mj-e-boc, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Used async and await with the fetch method to send and receive data (✅)) 👏
- The submit button hits the POST API endpoint👏
- The data submited reflect on the scoreboard 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
